/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppCatalystsRouteImport } from './routes/_app/catalysts'
import { Route as AppCryptoRouteImport } from './routes/_app/crypto'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppGoldRouteImport } from './routes/_app/gold'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMarketQuotesRouteImport } from './routes/api/market/quotes'
import { Route as ApiNewsCatalystsRouteImport } from './routes/api/news/catalysts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalystsRoute = AppCatalystsRouteImport.update({
  id: '/catalysts',
  path: '/catalysts',
  getParentRoute: () => AppRoute,
} as any)
const AppCryptoRoute = AppCryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppGoldRoute = AppGoldRouteImport.update({
  id: '/gold',
  path: '/gold',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketQuotesRoute = ApiMarketQuotesRouteImport.update({
  id: '/api/market/quotes',
  path: '/api/market/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsCatalystsRoute = ApiNewsCatalystsRouteImport.update({
  id: '/api/news/catalysts',
  path: '/api/news/catalysts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/catalysts': typeof AppCatalystsRoute
  '/crypto': typeof AppCryptoRoute
  '/dashboard': typeof AppDashboardRoute
  '/events': typeof AppEventsRoute
  '/gold': typeof AppGoldRoute
  '/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/market/quotes': typeof ApiMarketQuotesRoute
  '/api/news/catalysts': typeof ApiNewsCatalystsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/catalysts': typeof AppCatalystsRoute
  '/crypto': typeof AppCryptoRoute
  '/dashboard': typeof AppDashboardRoute
  '/events': typeof AppEventsRoute
  '/gold': typeof AppGoldRoute
  '/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/market/quotes': typeof ApiMarketQuotesRoute
  '/api/news/catalysts': typeof ApiNewsCatalystsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/catalysts': typeof AppCatalystsRoute
  '/_app/crypto': typeof AppCryptoRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/gold': typeof AppGoldRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/market/quotes': typeof ApiMarketQuotesRoute
  '/api/news/catalysts': typeof ApiNewsCatalystsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/catalysts'
    | '/crypto'
    | '/dashboard'
    | '/events'
    | '/gold'
    | '/settings'
    | '/api/health'
    | '/api/auth/$'
    | '/api/market/quotes'
    | '/api/news/catalysts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerts'
    | '/catalysts'
    | '/crypto'
    | '/dashboard'
    | '/events'
    | '/gold'
    | '/settings'
    | '/api/health'
    | '/api/auth/$'
    | '/api/market/quotes'
    | '/api/news/catalysts'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/alerts'
    | '/_app/catalysts'
    | '/_app/crypto'
    | '/_app/dashboard'
    | '/_app/events'
    | '/_app/gold'
    | '/_app/settings'
    | '/api/health'
    | '/api/auth/$'
    | '/api/market/quotes'
    | '/api/news/catalysts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMarketQuotesRoute: typeof ApiMarketQuotesRoute
  ApiNewsCatalystsRoute: typeof ApiNewsCatalystsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalysts': {
      id: '/_app/catalysts'
      path: '/catalysts'
      fullPath: '/catalysts'
      preLoaderRoute: typeof AppCatalystsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crypto': {
      id: '/_app/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof AppCryptoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gold': {
      id: '/_app/gold'
      path: '/gold'
      fullPath: '/gold'
      preLoaderRoute: typeof AppGoldRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/quotes': {
      id: '/api/market/quotes'
      path: '/api/market/quotes'
      fullPath: '/api/market/quotes'
      preLoaderRoute: typeof ApiMarketQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/catalysts': {
      id: '/api/news/catalysts'
      path: '/api/news/catalysts'
      fullPath: '/api/news/catalysts'
      preLoaderRoute: typeof ApiNewsCatalystsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppCatalystsRoute: typeof AppCatalystsRoute
  AppCryptoRoute: typeof AppCryptoRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEventsRoute: typeof AppEventsRoute
  AppGoldRoute: typeof AppGoldRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppCatalystsRoute: AppCatalystsRoute,
  AppCryptoRoute: AppCryptoRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEventsRoute: AppEventsRoute,
  AppGoldRoute: AppGoldRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMarketQuotesRoute: ApiMarketQuotesRoute,
  ApiNewsCatalystsRoute: ApiNewsCatalystsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
